// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn4mxOS9UckLjXLsmE9WuEo1D0PczOt9U',
    appId: '1:365407766304:web:2ef98b3bffaa4b10c9f945',
    messagingSenderId: '365407766304',
    projectId: 'vuyelwa-tutoring',
    authDomain: 'vuyelwa-tutoring.firebaseapp.com',
    storageBucket: 'vuyelwa-tutoring.appspot.com',
    measurementId: 'G-V4LPB2NX93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdR5jRtKgiFAdejG29yIThrwF9FnCLW9U',
    appId: '1:365407766304:android:5db8648b73b24534c9f945',
    messagingSenderId: '365407766304',
    projectId: 'vuyelwa-tutoring',
    storageBucket: 'vuyelwa-tutoring.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3xJo9oopMJ2rW2S6QC5N-Gq94Pf__vj0',
    appId: '1:365407766304:ios:75aad5cc64cb2f8bc9f945',
    messagingSenderId: '365407766304',
    projectId: 'vuyelwa-tutoring',
    storageBucket: 'vuyelwa-tutoring.appspot.com',
    iosClientId: '365407766304-dhqt5cgfh791bfmdssdkcgvbul5vm6k2.apps.googleusercontent.com',
    iosBundleId: 'com.vuyelwa.msVuyelwaRabolila',
  );
}
